apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-jobmanager
  template:
    metadata:
      labels:
        app: flink-jobmanager
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics' # Prometheus reporter default path
        prometheus.io/port: '9200' # Flink Prometheus reporter port
    spec:
      containers:
        - name: flink-jobmanager
          image: hyeneung/flink-sentiment-analyzer:latest
          imagePullPolicy: Always
          command: ["/docker-entrypoint.sh"]
          args: ["jobmanager"]
          ports:
            - containerPort: 8081 # Web UI
            - containerPort: 6123 # RPC port
            - containerPort: 9200 # Prometheus metrics port
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: "flink-jobmanager-service"
            - name: FLINK_PROPERTIES_web.port
              value: "8081"
            - name: FLINK_PROPERTIES_BLOB_SERVER_PORT
              value: "6124"
            - name: FLINK_PROPERTIES_METRICS_REPORTER_PROM_CLASS
              value: "org.apache.flink.metrics.prometheus.PrometheusReporter"
            - name: FLINK_PROPERTIES_METRICS_REPORTER_PROM_PORT
              value: "9200"
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-service
spec:
  selector:
    app: flink-jobmanager
  ports:
    - name: web
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: rpc
      protocol: TCP
      port: 6123
      targetPort: 6123
    - name: blob
      protocol: TCP
      port: 6124
      targetPort: 6124
    - name: metrics
      protocol: TCP
      port: 9200
      targetPort: 9200
