apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-jobmanager
  template:
    metadata:
      labels:
        app: flink-jobmanager
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics' # Prometheus reporter default path
        prometheus.io/port: '9200' # Flink Prometheus reporter port
    spec:
      containers:
        - name: flink-jobmanager
          image: hyeneung/flink-sentiment-analyzer:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Copy the config file from the read-only ConfigMap mount to the writable conf directory
              cp /opt/flink/conf-template/flink-conf.yaml /opt/flink/conf/flink-conf.yaml
              # Execute the original entrypoint script
              /docker-entrypoint.sh jobmanager
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: "flink-jobmanager-service"
          ports:
            - containerPort: 8081 # Web UI
            - containerPort: 6123 # RPC port
            - containerPort: 9200 # Prometheus metrics port
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf-template
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-service
spec:
  selector:
    app: flink-jobmanager
  ports:
    - name: web
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: rpc
      protocol: TCP
      port: 6123
      targetPort: 6123
    - name: blob
      protocol: TCP
      port: 6124
      targetPort: 6124
    - name: metrics
      protocol: TCP
      port: 9200
      targetPort: 9200
