apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 8 # Adjust as needed
  selector:
    matchLabels:
      app: flink-taskmanager
  template:
    metadata:
      labels:
        app: flink-taskmanager
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics' # Prometheus reporter default path
        prometheus.io/port: '9200' # Flink Prometheus reporter port
    spec:
      containers:
        - name: flink-taskmanager
          image: hyeneung/flink-sentiment-analyzer:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Copy the config file from the read-only ConfigMap mount to the writable conf directory
              cp /opt/flink/conf-template/flink-conf.yaml /opt/flink/conf/flink-conf.yaml
              # Execute the original entrypoint script
              /docker-entrypoint.sh taskmanager
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: "flink-jobmanager-service"
          ports:
            - containerPort: 9200 # Prometheus metrics port
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf-template
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config