apiVersion: v1
kind: Secret
metadata:
  name: cassandra
type: Opaque
stringData:
  cassandra-password: cassandra
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  jwt-secret-key: jwt-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: spark-openai-secret
type: Opaque
stringData:
  OPENAI_API_KEY: spark-openai-secret
